document.write("<footer class=\"footer_wrap\"  id=\"contact\">");
document.write("       <div class=\"container\">");
document.write("           <div class=\"row\">");
document.write("               <div class=\"col-lg-5 col-md-12 col-sm-6 col-xs-12\">");
document.write("                   <div class=\"footer_single_item pr_100 wow fadeInUp\">");
document.write("                       <div class=\"footer_logo\">");
document.write("                           <a href=\"#\">");
document.write("                               <img src=\"assets/images/logo.png\" alt=\"logo\">");
document.write("                           </a>");
document.write("                       </div>");
document.write("                       <p class=\"footer_content\">Mera Farmhouse is a one stop solution for farmers and agri-product sellers</p>");
document.write("                       <p class=\"copy_right mb_hide\">© 2023 Mera Farmhouse, All Rights Reserved</p>                        ");
document.write("                   </div>");
document.write("               </div>");
document.write("               <div class=\"col-lg-4 col-md-6 col-sm-6 col-xs-12\">");
document.write("                   <div class=\"footer_single_item wow fadeInUp\">");
document.write("                       <h3 class=\"footer_title\">Links</h3>");
document.write("                       <div class=\"row\">");
document.write("                           <div class=\"col-md-6 col-sm-6 col-xs-12\">");
document.write("                               <ul class=\"footer_menu\">");
document.write("                                   <li><a href=\"index.html\">Home</a></li>                                    ");
document.write("                                   <li><a href=\"terms.html\">Terms</a></li>");
document.write("                                   <li><a href=\"privacy.html\">Privacy</a></li>                                                                        ");
document.write("                                   <li><a href=\"contact.html\">Contact Us</a></li>");
document.write("                               </ul>");
document.write("                           </div>                            ");
document.write("                       </div>");
document.write("                   </div>");
document.write("               </div>");
document.write("               <div class=\"col-lg-3 col-md-6 col-sm-6 col-xs-12\">");
document.write("                   <div class=\"footer_single_item wow fadeInUp\">");
document.write("                       <h3 class=\"footer_title\">Contact Info</h3>");
document.write("                       <ul class=\"contact_address\">");
document.write("                           <li>");
document.write("                               <span class=\"address_left\">Address:</span>");
document.write("                               <span class=\"address_right\">Plot 379,<br> Industrial Area Phase II,<br> Chandigarh-160002,<br> India</span>");
document.write("                           </li>                           ");
document.write("                           <li>");
document.write("                               <span class=\"address_left\">E-mail:</span>");
document.write("                               <span class=\"address_right\"><a href=\"mailto:info@merafarmhouse.com\">info@merafarmhouse.com</a> </span>");
document.write("                           </li>");
document.write("                           <li>");
document.write("                               <span class=\"address_left\">Phone:</span>");
document.write("                               <span class=\"address_right\">+91-987-596-8172</span>");
document.write("                           </li>");

document.write("                       </ul>");
document.write("                       <!--<ul class=\"footer_social_menu\">");
document.write("                           <li><a href=\"#\"><i class=\"social_facebook\"></i></a></li>");
document.write("                           <li><a href=\"#\"><i class=\"social_twitter\"></i></a></li>");
document.write("                           <li><a href=\"#\"><i class=\"social_pinterest\"></i></a></li>");
document.write("                           <li><a href=\"#\"><i class=\"social_linkedin\"></i></a></li>");
document.write("                       </ul>-->");
document.write("                   </div>");
document.write("               </div>                ");
document.write("           </div>");
document.write("       </div>");
document.write("   </footer>");